services:
  auth_service:
    build:
      context: ../..
      dockerfile: deployment/development/Dockerfile
    env_file:
      - ./.env.development
    ports:
      - "60000:60000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: postgres_container
    env_file:
      - ./.env.development
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
